import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.css";

export const metadata = {
	title: "Albion Square | Find the perfect Albion Online guild",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="dark:bg-gray-900">
			<body>
				{children}
				<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
			</body>
		</html>
	);
}
