version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:cockroachdb

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  cockroachdb:
    image: cockroachdb/cockroach:latest
    restart: unless-stopped
    volumes:
      - "cockroach-data:/cockroach/cockroach-data"
    network_mode: service:localstack
    command: start-single-node --insecure

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dev
      - AWS_SECRET_ACCESS_KEY=dev
      - HOSTNAME=localhost
      - USE_SSL=false
    volumes:
      - "localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  cockroach-data:
  localstack-data:
